import type { Scene } from '../store/useStudioStore';

export interface ExportContext {
  topic: string;
  projectClass: string;
  cast: string;
  worldId: string;
  refId: string;
  paletteId: string;
}

function csvEscape(v: string): string {
  if (/[";\n]/.test(v)) return `"${v.replace(/"/g, '""')}"`;
  return v;
}

/** CSV with semicolon separator — friendly to Turkish Excel locales. */
export function scenesToCSV(scenes: Scene[], ctx: ExportContext): string {
  const header = [
    'Sahne',
    'Faz',
    'Süre (s)',
    'Yoğunluk',
    'Beat',
    'Dominant',
    'Olay',
    'Vantage',
    'Image Prompt',
    'Voice Over',
    'Suno Brief',
    'Fingerprint',
  ];
  const rows = scenes.map((s) => [
    s.id,
    s.phaseName,
    s.durationSec,
    Math.round(s.intensity),
    s.architecture.beat,
    s.architecture.dominantSubject,
    s.architecture.event,
    s.architecture.imageVantage,
    s.imagePrompt,
    s.voiceOver,
    s.sunoBrief,
    s.architecture.semanticFingerprint,
  ]);
  const lines = [header.join(';'), ...rows.map((r) => r.map((c) => csvEscape(String(c))).join(';'))];
  const banner = [
    `# MAMILAS Timeline — ${ctx.topic}`,
    `# Class: ${ctx.projectClass} · Cast: ${ctx.cast} · World: ${ctx.worldId}`,
    `# Ref: ${ctx.refId || '—'} · Palette: ${ctx.paletteId || 'world default'}`,
    `# Generated by mamilas-modern (pure.ts)`,
    '',
  ];
  return banner.join('\n') + lines.join('\n') + '\n';
}

/** Markdown for production teams reading PR descriptions / Notion etc. */
export function scenesToMarkdown(scenes: Scene[], ctx: ExportContext): string {
  const head = [
    `# ${ctx.topic}`,
    '',
    `**Class:** \`${ctx.projectClass}\` · **Cast:** \`${ctx.cast}\` · **World:** \`${ctx.worldId}\``,
    `**Reference DNA:** \`${ctx.refId || 'none'}\` · **Palette:** \`${ctx.paletteId || 'world default'}\``,
    `**Total:** ${scenes.length} sahne · ${scenes.reduce((a, b) => a + b.durationSec, 0)}s`,
    '',
    '---',
    '',
  ];

  const body = scenes
    .map((s) => {
      return [
        `## Sahne ${s.id} · ${s.phaseName} · ${s.durationSec}s`,
        '',
        `- **Beat:** ${s.architecture.beat}`,
        `- **Dominant subject:** ${s.architecture.dominantSubject}`,
        `- **Event:** ${s.architecture.event}`,
        `- **Vantage:** \`${s.architecture.imageVantage}\``,
        `- **Fingerprint:** \`${s.architecture.semanticFingerprint}\``,
        '',
        '### Image prompt',
        '```',
        s.imagePrompt,
        '```',
        '',
        '### Voice-over',
        `> ${s.voiceOver}`,
        '',
        '### Suno brief',
        '```',
        s.sunoBrief,
        '```',
        '',
      ].join('\n');
    })
    .join('\n');

  return head.join('\n') + body;
}
