import type { Scene } from '../store/useStudioStore';

export interface ExportContext {
  topic: string;
  projectClass: string;
  cast: string;
  worldId: string;
  refIds: string[];
  paletteId: string;
}

function csvEscape(v: string): string {
  if (/[";\n]/.test(v)) return `"${v.replace(/"/g, '""')}"`;
  return v;
}

const MIME_EXTENSIONS: Array<[RegExp, string]> = [
  [/json/i, '.json'],
  [/csv/i, '.csv'],
  [/markdown|md/i, '.md'],
  [/text\/plain/i, '.txt'],
];
const EXPORT_SUFFIXES = ['_production', '_mamilas_command', '_handoff_packets', '_timeline', '_scenes'];

function limitDownloadBase(base: string, maxLength = 120): string {
  if (base.length <= maxLength) return base;
  const suffix = EXPORT_SUFFIXES.find((candidate) => base.endsWith(candidate));
  if (!suffix) return base.slice(0, maxLength).replace(/[._-]+$/g, '');
  const prefixLength = Math.max(1, maxLength - suffix.length);
  const prefix = base.slice(0, prefixLength).replace(/[._-]+$/g, '');
  return `${prefix}${suffix}`;
}

export function normalizeDownloadName(name: string, mime: string): string {
  const extension = MIME_EXTENSIONS.find(([pattern]) => pattern.test(mime))?.[1] || '';
  const rawName = String(name || 'mamilas').trim() || 'mamilas';
  const withExtension = extension && !rawName.toLowerCase().endsWith(extension) ? `${rawName}${extension}` : rawName;
  const dotIndex = withExtension.lastIndexOf('.');
  const base = dotIndex > 0 ? withExtension.slice(0, dotIndex) : withExtension;
  const ext = dotIndex > 0 ? withExtension.slice(dotIndex) : extension;
  const safeBase = base
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[<>:"/\\|?*\u0000-\u001f]+/g, '_')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/[._-]+$/g, '');
  return `${limitDownloadBase(safeBase || 'mamilas')}${ext || ''}`;
}

/** CSV with semicolon separator — friendly to Turkish Excel locales. */
export function scenesToCSV(scenes: Scene[], ctx: ExportContext): string {
  const header = [
    'Sahne',
    'Faz',
    'Süre (s)',
    'Yoğunluk',
    'Beat',
    'Exact Source Beat',
    'Yorum Statüsü',
    'Vantage',
    'Image Prompt',
    'Voice Over',
    'On-Screen Text (baked)',
    'Suno Brief',
    'Fingerprint',
  ];
  const rows = scenes.map((s) => [
    s.id,
    s.phaseName,
    s.durationSec,
    Math.round(s.intensity),
    s.architecture.beat,
    s.architecture.exactSourceBeat,
    s.architecture.semanticInterpretationStatus,
    s.architecture.imageVantage,
    s.imagePrompt,
    s.voiceOver,
    s.onScreenText ?? '',
    s.sunoBrief,
    s.architecture.semanticFingerprint,
  ]);
  const lines = [header.join(';'), ...rows.map((r) => r.map((c) => csvEscape(String(c))).join(';'))];
  const banner = [
    `# MAMILAS Timeline — ${ctx.topic}`,
    `# Class: ${ctx.projectClass} · Cast: ${ctx.cast} · World: ${ctx.worldId}`,
    `# Ref: ${ctx.refIds?.join(', ') || '—'} · Palette: ${ctx.paletteId || 'world default'}`,
    `# Generated by mamilas-modern (pure.ts)`,
    '',
  ];
  return banner.join('\n') + lines.join('\n') + '\n';
}

/** Markdown for production teams reading PR descriptions / Notion etc. */
export function scenesToMarkdown(scenes: Scene[], ctx: ExportContext): string {
  const head = [
    `# ${ctx.topic}`,
    '',
    `**Class:** \`${ctx.projectClass}\` · **Cast:** \`${ctx.cast}\` · **World:** \`${ctx.worldId}\``,
    `**Reference DNA:** \`${ctx.refIds?.join(', ') || 'none'}\` · **Palette:** \`${ctx.paletteId || 'world default'}\``,
    `**Total:** ${scenes.length} sahne · ${scenes.reduce((a, b) => a + b.durationSec, 0)}s`,
    '',
    '---',
    '',
  ];

  const body = scenes
    .map((s) => {
      return [
        `## Sahne ${s.id} · ${s.phaseName} · ${s.durationSec}s`,
        '',
        '| Property | Assignment |',
        '|---|---|',
        `| **Beat** | ${s.architecture.beat} |`,
        `| **Exact source beat** | ${s.architecture.exactSourceBeat} |`,
        `| **Yorum** | \`${s.architecture.semanticInterpretationStatus}\` — dominant özne/olay yorumu ajanın interpretation receipt'inde |`,
        `| **Vantage** | \`${s.architecture.imageVantage}\` |`,
        `| **Fingerprint** | \`${s.architecture.semanticFingerprint}\` |`,
        '',
        '### Image prompt',
        '```',
        s.imagePrompt,
        '```',
        '',
        '### Voice-over',
        `> ${s.voiceOver}`,
        '',
        ...(s.onScreenText
          ? ['### On-Screen Text (baked)', `> **"${s.onScreenText}"** — diegetic or designed typography baked into the Image prompt start frame. No post-production overlay downstream.`, '']
          : ['### On-Screen Text', '> _NO_TEXT — the image carries the meaning_', '']),
        '### Suno brief', '```', s.sunoBrief, '```', '',
      ].join('\n');
    })
    .join('\n');

  return head.join('\n') + body;
}

export function downloadFile(name: string, content: string, mime: string) {
  const type = mime.includes('charset=') ? mime : `${mime};charset=utf-8`;
  const filename = normalizeDownloadName(name, type);
  const file = typeof File === 'undefined'
    ? new Blob([content], { type })
    : new File([content], filename, { type });
  const url = URL.createObjectURL(file);
  const a = document.createElement('a');
  a.href = url;
  a.rel = 'noopener';
  a.download = filename;
  a.setAttribute('download', filename);
  a.setAttribute('type', type);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
